name: Test build

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: yarn install
      - run: yarn build && yarn package

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./
        with:
          queue_name: 'library update - library-aaa'
          action: 'next-job'
